# Generated by Django 3.1.7 on 2021-04-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XKCDComicViews',
            fields=[
                ('comic_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
